// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwjgvrgpfwvilvnathkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3amd2cmdwZnd2aWx2bmF0aGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjcxMDksImV4cCI6MjA2NDQ0MzEwOX0.Dv5CtPSGk30Mv0F_nkcmlbqOa63pjiJXAOBIuLDfc_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);